
// von Julian Pröhl, Matthias Escher
// von Markus Overberg, Marc Czolbe
package stockmanagement;

import entity.Lage;
import java.util.ArrayList;
import lists.ArtiList;
import lists.LageList;

public class EditOKLagerortMetadaten extends javax.swing.JFrame {

    LagerGUI lagergui;
    Lage lage;
    Integer LNR;
    Integer Regal;
    Integer Fach;
    Integer MaxMenge;
    ArtiList ArtiListe;

    /**
     * Creates new form LagerfachEditGUI
     */
    public EditOKLagerortMetadaten() {
        initComponents();
    }

    public EditOKLagerortMetadaten(LagerGUI lagergui, Lage lage) {
        initComponents();
        this.lagergui = lagergui;
        this.lage = lage;
        this.LNR = lage.getLNr();
        this.Regal = lage.getRegal();
        this.Fach = lage.getFach();
        this.MaxMenge = lage.getMaxmenge();
        String str = "FROM Arti Where F_LNr = " + LNR;
        ArtiListe = new ArtiList(str);

        Label_LNR.setText(this.LNR.toString());
        tfFach.setText(this.Fach.toString());
        tfRegal.setText(this.Regal.toString());
        tfmaxMenge.setText(this.MaxMenge.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFach = new javax.swing.JLabel();
        labelMaxM = new javax.swing.JLabel();
        tfRegal = new javax.swing.JTextField();
        tfFach = new javax.swing.JTextField();
        tfmaxMenge = new javax.swing.JTextField();
        Label_LNR = new javax.swing.JLabel();
        buttonAbbrechen = new javax.swing.JButton();
        buttonLagerAnlegenOK = new javax.swing.JButton();
        labelL_anlegen = new javax.swing.JLabel();
        labelLagerort = new javax.swing.JLabel();
        labelRegal = new javax.swing.JLabel();

        labelFach.setText("Fach:");

        labelMaxM.setText("Max. Menge:");

        Label_LNR.setText("jLabel1");

        buttonAbbrechen.setText("Abbrechen");
        buttonAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbbrechenActionPerformed(evt);
            }
        });

        buttonLagerAnlegenOK.setText("OK");
        buttonLagerAnlegenOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLagerAnlegenOKActionPerformed(evt);
            }
        });

        labelL_anlegen.setText("Lagerort bearbeiten");

        labelLagerort.setText("Lagerortnummer:");

        labelRegal.setText("Regal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAbbrechen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRegal)
                            .addComponent(labelLagerort)
                            .addComponent(labelFach)
                            .addComponent(labelMaxM)
                            .addComponent(labelL_anlegen))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRegal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonLagerAnlegenOK)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfFach)
                            .addComponent(tfmaxMenge))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Label_LNR)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelL_anlegen)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLagerort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRegal)
                            .addComponent(tfRegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFach)
                            .addComponent(tfFach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaxM)
                            .addComponent(tfmaxMenge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAbbrechen)
                            .addComponent(buttonLagerAnlegenOK)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Label_LNR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLagerAnlegenOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLagerAnlegenOKActionPerformed
        bearbeiten();
    }//GEN-LAST:event_buttonLagerAnlegenOKActionPerformed

    private void buttonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbbrechenActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonAbbrechenActionPerformed

    
        //Methode zum bearbeiten der Regal/Fach Kombination
        //Zuvor wird überprüft, ob die Eingaben positiv sind und ob die überhaupt Zahlen eingebgen wurden.
        //Bevor die Datenbank aktualisiert wird, findet noch eine Überprüfung statt, ob die Regal/Fach-Kombination 
        //bereits vorhanden ist
        //Abschließend wird die Tabelle aktualisiert und die GUI geschlossen
    private void bearbeiten() {

        Integer EditRegal = 0;
        Integer EditFach = 0;
        Integer EditmaxMenge = 0;
        Boolean succes = true;
        ArrayList<Integer> list = new ArrayList<Integer>();
        Lage lager = new Lage();
        LageList LagerList;
        int ArtiBestandsmenge = 0;

        try {
            EditRegal = Integer.parseInt(tfRegal.getText());
            EditFach = Integer.parseInt(tfFach.getText());
            EditmaxMenge = Integer.parseInt(tfmaxMenge.getText());

        } catch (NumberFormatException e) {
            general.Message.showError("Fehler!", "Bitte nur Zahlen eingeben");
            succes = false;
        }

        LagerList = new LageList("FROM Lage Where Regal = " + EditRegal + " and Fach = " + EditFach);

        if (succes) {
            list.add(EditFach);
            list.add(EditRegal);
            list.add(EditmaxMenge);

            if (!general.Check.istNegativ(list)) {
                String UpdateString = "UPDATE Lage SET";

                try {

                    ArtiBestandsmenge = ArtiListe.getBESTANDSMENGE(0);

                } catch (IndexOutOfBoundsException e) {

                }

                if (EditmaxMenge >= ArtiBestandsmenge) {

                    if (LagerList.getsize() == 0) {

                        if (!(this.Fach.equals(EditFach))) {
                            UpdateString = UpdateString + " Fach=" + EditFach;
                        }

                        if (!(this.Regal.equals(EditRegal))) {
                            if (!(this.Fach.equals(EditFach))) {
                                UpdateString = UpdateString + ",Regal=" + EditRegal;
                            } else {
                                UpdateString = UpdateString + " Regal=" + EditRegal;
                            }
                        }
                    } else if (!(this.Fach.equals(EditFach)) || !(this.Regal.equals(EditRegal))) {
                        general.Message.showError("Fehler!", "Die Lagerplatzkommbination ist schon vergeben! Die Lagerplatznummer lautet " + LagerList.getLNr(0));
                    }

                    if (!(this.MaxMenge.equals(EditmaxMenge))) {
                        if (!(this.Fach.equals(EditFach)) || !(this.Regal.equals(EditRegal))) {
                            UpdateString = UpdateString + ",maxmenge=" + EditmaxMenge;
                        } else {
                            UpdateString = UpdateString + " maxmenge=" + EditmaxMenge;
                        }
                    }
                    if (!UpdateString.equals("UPDATE Lage SET")) {
                        int wert = lage.updateLage(UpdateString);
                        try {
                            if (!(this.Fach.equals(EditFach)) || !(this.Regal.equals(EditRegal))) {
                                general.Message.showSuccess("Erfolgreich", "Die Aktualisierung war Erfolgreich!\nAchtung! Der Artikel \"" + ArtiListe.getBezeichnung(0) + "\" mit der Nummer " + ArtiListe.getANR(0) + " liegt nun in einem neuen Fach!");
                            }
                        } catch (IndexOutOfBoundsException e) {

                        }
                        setVisible(false);
                        lagergui.TabelleHolen();
                        lagergui.Tabelleausgeben();
                    }

                } else {
                    general.Message.showError("Fehler", "Die maximale Fachmenge darf nicht kleiner sein, als der vorhandene Inhalt in dem Fach!");
                }
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOKLagerortMetadaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOKLagerortMetadaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOKLagerortMetadaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOKLagerortMetadaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOKLagerortMetadaten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_LNR;
    private javax.swing.JButton buttonAbbrechen;
    private javax.swing.JButton buttonLagerAnlegenOK;
    private javax.swing.JLabel labelFach;
    private javax.swing.JLabel labelL_anlegen;
    private javax.swing.JLabel labelLagerort;
    private javax.swing.JLabel labelMaxM;
    private javax.swing.JLabel labelRegal;
    private javax.swing.JTextField tfFach;
    private javax.swing.JTextField tfRegal;
    private javax.swing.JTextField tfmaxMenge;
    // End of variables declaration//GEN-END:variables

}
