/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import customermanagement.customerGUI;
import report.ReportMainGUI;
import stockmanagement.LagerverwaltungGUI;

/**
 *
 * @author Markus
 */

// Klasse WaWiMainGUI
// Hauptmenü des Warenwirtschaftssystems
// Von diesem Hauptmenü gelangt man in die Unterbereiche:
//      -Lagerverwaltung
//      -Kundenverwaltung
//      -Report
public class WaWiMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form WaWiGUI
     */
    public WaWiMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonReport = new javax.swing.JButton();
        buttonLager = new javax.swing.JButton();
        labelWaWi = new javax.swing.JLabel();
        buttonKundenverwaltung = new javax.swing.JButton();
        buttonBenutzerverwaltung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menü");
        setSize(new java.awt.Dimension(800, 600));

        buttonReport.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonReport.setText("Report");
        buttonReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReportActionPerformed(evt);
            }
        });

        buttonLager.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonLager.setText("Lagerverwaltung");
        buttonLager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLagerActionPerformed(evt);
            }
        });

        labelWaWi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelWaWi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWaWi.setText("Warenwirtschaftssystem");

        buttonKundenverwaltung.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonKundenverwaltung.setText("Kundenverwaltung");
        buttonKundenverwaltung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonKundenverwaltung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKundenverwaltungActionPerformed(evt);
            }
        });

        buttonBenutzerverwaltung.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buttonBenutzerverwaltung.setText("Benutzerverwaltung");
        buttonBenutzerverwaltung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonKundenverwaltung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBenutzerverwaltung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addComponent(labelWaWi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelWaWi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(buttonLager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBenutzerverwaltung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonKundenverwaltung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReport)
                .addGap(48, 48, 48))
        );

        buttonReport.getAccessibleContext().setAccessibleName("buttonReport");
        buttonLager.getAccessibleContext().setAccessibleName("buttonLager");
        labelWaWi.getAccessibleContext().setAccessibleName("labelWaWi");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Methode buttonLagerActionPerformed
    // Sobald der Button "Lagerverwaltung" gedrückt wird, wird ein Objekt der
    // Klasse LagerverwaltungGUI erzeugt. Die aktuelle Ansicht wird ausgeblendet
    // und die Ansicht zur Lagerverwaltung eingeblendet
    // Übergabeparameter: Button Clickevent
    private void buttonLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLagerActionPerformed
        setVisible(false);
        // Objekt der Klasse LagerverwaltungGUI erzeugen
        LagerverwaltungGUI lGUI = new LagerverwaltungGUI();
        lGUI.setVisible(true);

    }//GEN-LAST:event_buttonLagerActionPerformed

    // Methode buttonReportActionPerformed
    // Sobald der Button "Report" gedrückt wird, wird ein Objekt der
    // Klasse ReportMainGUI erzeugt. Die aktuelle Ansicht wird ausgeblendet
    // und die Ansicht zum Anzeigen von Reports eingeblendet
    // Übergabeparameter: Button Clickevent
    private void buttonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReportActionPerformed
        setVisible(false);
        // Objekt der Klasse ReportMainGUI erzeugen
        ReportMainGUI rGUI = new ReportMainGUI();
        rGUI.setVisible(true);
    }//GEN-LAST:event_buttonReportActionPerformed

    // Methode buttonKundenverwaltungActionPerformed
    // Sobald der Button "Kundenverwaltung" gedrückt wird, wird ein Objekt der
    // Klasse customerGUI erzeugt. Die aktuelle Ansicht wird ausgeblendet
    // und die Ansicht zur Kundenverwaltung eingeblendet
    // Es wird die Methode "tabelleausgeben" aufgerufen, sodass die Kundendaten
    // in der Kundenverwaltungsansicht angezeigt werden.
    // Übergabeparameter: Button Clickevent
    private void buttonKundenverwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKundenverwaltungActionPerformed
        setVisible(false);
        // Objekt der Klasse customerGUI erzeugen
        customerGUI cGUI = new customerGUI();
        cGUI.setVisible(true);
        // Methode zum Ausgeben der Kundendaten aufrufen
        cGUI.tabelleausgeben();
    }//GEN-LAST:event_buttonKundenverwaltungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaWiMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaWiMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaWiMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaWiMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        database.DB_Connect.ConnectOpen();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaWiMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBenutzerverwaltung;
    private javax.swing.JButton buttonKundenverwaltung;
    private javax.swing.JButton buttonLager;
    private javax.swing.JButton buttonReport;
    private javax.swing.JLabel labelWaWi;
    // End of variables declaration//GEN-END:variables
}
