/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reports;

import gui.WaWiMainGUI;

/**
 *
 * @author Markus
 */
public class ReportMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form ReportGUI
     */
    public ReportMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelReports = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        buttonShowArtikelliste = new javax.swing.JButton();
        buttonShowbestellungen = new javax.swing.JButton();
        buttonShowLagerbestand = new javax.swing.JButton();
        buttonShowBestellvolumen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelReports.setText("Reports");

        buttonBack.setText("Zurück");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonShowArtikelliste.setLabel("Artikelliste");
        buttonShowArtikelliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowArtikellisteActionPerformed(evt);
            }
        });

        buttonShowbestellungen.setText("Offene Bestellungen");
        buttonShowbestellungen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowbestellungenActionPerformed(evt);
            }
        });

        buttonShowLagerbestand.setText("Lagerbestand");
        buttonShowLagerbestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowLagerbestandActionPerformed(evt);
            }
        });

        buttonShowBestellvolumen.setText("Bestellvolumen");
        buttonShowBestellvolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowBestellvolumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addGap(54, 54, 54)
                        .addComponent(labelReports))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonShowBestellvolumen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonShowLagerbestand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonShowbestellungen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonShowArtikelliste, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(558, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(labelReports))
                .addGap(26, 26, 26)
                .addComponent(buttonShowArtikelliste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonShowbestellungen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonShowLagerbestand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonShowBestellvolumen)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        labelReports.getAccessibleContext().setAccessibleName("labelReports");
        buttonBack.getAccessibleContext().setAccessibleName("buttonBack");
        buttonShowArtikelliste.getAccessibleContext().setAccessibleName("buttonShowArtikelliste");
        buttonShowbestellungen.getAccessibleContext().setAccessibleName("buttonBestellungen");
        buttonShowLagerbestand.getAccessibleContext().setAccessibleName("buttonLagerbestand");
        buttonShowBestellvolumen.getAccessibleContext().setAccessibleName("buttonShowBestellvolumen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        setVisible(false);
        WaWiMainGUI wawiGUI = new WaWiMainGUI();
        wawiGUI.setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonShowArtikellisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowArtikellisteActionPerformed
      setVisible(false);
      ArtikellisteGUI showArtGUI = new ArtikellisteGUI();
      showArtGUI.setVisible(true);
    }//GEN-LAST:event_buttonShowArtikellisteActionPerformed

    private void buttonShowbestellungenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowbestellungenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonShowbestellungenActionPerformed

    private void buttonShowLagerbestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowLagerbestandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonShowLagerbestandActionPerformed

    private void buttonShowBestellvolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowBestellvolumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonShowBestellvolumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonShowArtikelliste;
    private javax.swing.JButton buttonShowBestellvolumen;
    private javax.swing.JButton buttonShowLagerbestand;
    private javax.swing.JButton buttonShowbestellungen;
    private javax.swing.JLabel labelReports;
    // End of variables declaration//GEN-END:variables
}
