/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lagerverwaltung;

import gui.WaWiMainGUI;

/**
 *
 * @author Markus
 */
public class LagerverwaltungGUI extends javax.swing.JFrame {

    /**
     * Creates new form LagerGUI
     */
    public LagerverwaltungGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonEinlagern = new javax.swing.JButton();
        buttonPicklist = new javax.swing.JButton();
        buttonKorrektur = new javax.swing.JButton();
        buttonBestand = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonAnlegen = new javax.swing.JButton();
        buttonAuslagern = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(725, 500));

        jLabel1.setText("Hauptdialog");

        jLabel2.setText("Lagerverwaltung");

        buttonEinlagern.setText("Artikel einlagern");
        buttonEinlagern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEinlagernActionPerformed(evt);
            }
        });

        buttonPicklist.setText("Neue Pickinglist");
        buttonPicklist.setName(""); // NOI18N
        buttonPicklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPicklistActionPerformed(evt);
            }
        });

        buttonKorrektur.setText("Bestandskorrektur");
        buttonKorrektur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKorrekturActionPerformed(evt);
            }
        });

        buttonBestand.setText("Bestand anzeigen");
        buttonBestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBestandActionPerformed(evt);
            }
        });

        buttonBack.setText("Zurück");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonDelete.setText("Artikel/Lagerplätze löschen");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonAnlegen.setText("Artikel/Lagerplätze anlegen");
        buttonAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnlegenActionPerformed(evt);
            }
        });

        buttonAuslagern.setText("Artikel auslagern");
        buttonAuslagern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAuslagernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonAuslagern, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEinlagern, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPicklist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAnlegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonKorrektur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBestand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(23, 385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEinlagern)
                    .addComponent(buttonKorrektur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPicklist)
                    .addComponent(buttonBestand))
                .addGap(18, 18, 18)
                .addComponent(buttonAuslagern)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(buttonAnlegen))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("labelLagerHaupt");
        jLabel2.getAccessibleContext().setAccessibleName("labelLager");
        buttonEinlagern.getAccessibleContext().setAccessibleName("buttonEinlagern");
        buttonPicklist.getAccessibleContext().setAccessibleName("buttonPicklist");
        buttonKorrektur.getAccessibleContext().setAccessibleName("buttonKorrektur");
        buttonBestand.getAccessibleContext().setAccessibleName("buttonBestand");
        buttonBack.getAccessibleContext().setAccessibleName("buttonBack");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPicklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPicklistActionPerformed
        setVisible(false);
        picklistGUI pickshowGUI = new picklistGUI();
        pickshowGUI.setVisible(true);
    }//GEN-LAST:event_buttonPicklistActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        setVisible(false);
        WaWiMainGUI wawiGUI = new WaWiMainGUI();
        wawiGUI.setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonBestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBestandActionPerformed
      setVisible(false);
      ArtikelbestandGUI bestandGUI = new ArtikelbestandGUI();
        bestandGUI.setVisible(true);
        bestandGUI.Tabelleausgeben();
    }//GEN-LAST:event_buttonBestandActionPerformed

    private void buttonEinlagernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEinlagernActionPerformed
      setVisible(false);
      EinlagernGUI einlGUI = new EinlagernGUI();
      einlGUI.setVisible(true);
    }//GEN-LAST:event_buttonEinlagernActionPerformed

    private void buttonKorrekturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKorrekturActionPerformed
      setVisible(false);
      KorrekturGUI korrGUI = new KorrekturGUI();
      korrGUI.setVisible(true);
    }//GEN-LAST:event_buttonKorrekturActionPerformed

    private void buttonAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnlegenActionPerformed
      setVisible(false);
      AnlegenGUI anlegGUI = new AnlegenGUI();
      anlegGUI.setVisible(true);
    }//GEN-LAST:event_buttonAnlegenActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
      setVisible(false);
      DeleteGUI loeschGUI = new DeleteGUI();
      loeschGUI.setVisible(true);
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonAuslagernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAuslagernActionPerformed
      setVisible(false);
      AuslagernGUI auslagerGUI = new AuslagernGUI();
      auslagerGUI.setVisible(true);
    }//GEN-LAST:event_buttonAuslagernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LagerverwaltungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LagerverwaltungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LagerverwaltungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LagerverwaltungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LagerverwaltungGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnlegen;
    private javax.swing.JButton buttonAuslagern;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonBestand;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEinlagern;
    private javax.swing.JButton buttonKorrektur;
    private javax.swing.JButton buttonPicklist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
